age: 25
defaultage: 18
descriptiontag: true
expandedtags: true
cats:
- Cauchy
- Plato
pi: 3.14
perfection:
- 6
- 28
- 496
- 8128
dob: 1987-07-05T05:45:00Z
sub:
- weight: 55
  height: 200
- weight: 55
  height: 100
- weight: 55
  height: 300
submap:
  "1":
    weight: 0
    height: 200
  "2":
    weight: 0
    height: 100
  "4":
    weight: 0
    height: 300
